"""
Report generators — HTML and JSON output for drift findings.
HTML report is designed to be emailed or saved as an artifact.
"""

import json
from datetime import datetime
from src.drift_engine import DriftReport, Severity


class HTMLReporter:
    def generate(self, report: DriftReport) -> str:
        findings_html = ""
        for f in sorted(report.findings, key=lambda x: ["critical","warning","info"].index(x.severity.value)):
            colour = {"critical": "#fee2e2", "warning": "#fef9c3", "info": "#f0f9ff"}[f.severity.value]
            badge_colour = {"critical": "#dc2626", "warning": "#ca8a04", "info": "#0284c7"}[f.severity.value]
            remediated_badge = (
                '<span style="background:#d1fae5;color:#065f46;padding:2px 8px;border-radius:12px;font-size:11px;margin-left:8px">✓ remediated</span>'
                if f.remediated else ""
            )
            findings_html += f"""
            <tr style="background:{colour}">
              <td style="padding:10px 12px">
                <span style="background:{badge_colour};color:white;padding:2px 8px;border-radius:12px;font-size:11px;font-weight:500">{f.severity.value.upper()}</span>
                {remediated_badge}
              </td>
              <td style="padding:10px 12px;font-family:monospace;font-size:13px">{f.resource_id}</td>
              <td style="padding:10px 12px;font-size:13px">{f.resource_type.value}</td>
              <td style="padding:10px 12px;font-size:13px">{f.description}</td>
              <td style="padding:10px 12px;font-size:12px;color:#6b7280">{f.detected_at[:19]}</td>
            </tr>"""

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Infrastructure Drift Report — {report.account_id}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 32px; background: #f9fafb; color: #111; }}
  .container {{ max-width: 1100px; margin: 0 auto; }}
  h1 {{ font-size: 22px; font-weight: 600; margin: 0 0 4px; }}
  .meta {{ color: #6b7280; font-size: 14px; margin-bottom: 32px; }}
  .summary {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 32px; }}
  .card {{ background: white; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; text-align: center; }}
  .card-val {{ font-size: 28px; font-weight: 600; }}
  .card-lbl {{ font-size: 12px; color: #6b7280; margin-top: 4px; }}
  .critical {{ color: #dc2626; }}
  .warning  {{ color: #ca8a04; }}
  .info     {{ color: #0284c7; }}
  .green    {{ color: #16a34a; }}
  table {{ width: 100%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; border: 1px solid #e5e7eb; }}
  th {{ background: #f3f4f6; padding: 10px 12px; text-align: left; font-size: 12px; font-weight: 500; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; }}
  tr:not(:last-child) {{ border-bottom: 1px solid #e5e7eb; }}
  .footer {{ margin-top: 24px; font-size: 12px; color: #9ca3af; }}
</style>
</head>
<body>
<div class="container">
  <h1>Infrastructure Drift Report</h1>
  <div class="meta">Account: {report.account_id} &nbsp;|&nbsp; Region: {report.region} &nbsp;|&nbsp; Scanned: {report.scanned_at[:19]} UTC</div>

  <div class="summary">
    <div class="card"><div class="card-val">{len(report.findings)}</div><div class="card-lbl">Total findings</div></div>
    <div class="card"><div class="card-val critical">{report.critical_count}</div><div class="card-lbl">Critical</div></div>
    <div class="card"><div class="card-val warning">{report.warning_count}</div><div class="card-lbl">Warnings</div></div>
    <div class="card"><div class="card-val green">{report.remediated_count}</div><div class="card-lbl">Auto-remediated</div></div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Severity</th>
        <th>Resource ID</th>
        <th>Type</th>
        <th>Description</th>
        <th>Detected at</th>
      </tr>
    </thead>
    <tbody>
      {findings_html if findings_html else '<tr><td colspan="5" style="padding:24px;text-align:center;color:#6b7280">No drift detected ✓</td></tr>'}
    </tbody>
  </table>

  <div class="footer">Generated by infra-drift-detector &nbsp;|&nbsp; github.com/apoorvup07/infra-drift-detector</div>
</div>
</body>
</html>"""


class JSONReporter:
    def generate(self, report: DriftReport) -> str:
        return json.dumps(report.to_dict(), indent=2, default=str)
